[package]
name = "openctf"
version = "0.1.0"
authors = ["Michael Zhang"]

[[bin]]
name = "openctf"
path = "cli/main.rs"

[dependencies]
actix = "0.7.0"
actix-web = "0.6.15"
cfg-if = "0.1.4"
diesel = { version = "1.3.2", features = ["postgres", "r2d2", "sqlite"] }
either = "1.5.0"
env_logger = "0.5.10"
failure = "0.1.1"
r2d2 = "0.8.2"
regex = "1.0.1"
rust-embed = "3.0.0"
structopt = "0.2.10"
tera = "0.11.8"
walkdir = "2.1.4"
wtforms = "0.0"
# wtforms = { path = "../wtforms" }
