[package]
name = "filestore"
version = "0.1.0"
authors = ["Michael Zhang <failed.down@gmail.com>"]

[features]
default = ["server"]
server = []

[dependencies]
actix-web = "0.7"
bytes = "0.4"
env_logger = "0.5"
failure = "0.1"
futures = "0.1"
http = "0.1"
hyper = "0.12"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.2"
